"""asset probe fields

Revision ID: 77a80d748549
Revises: 86eae84a81b8
Create Date: 2026-09-13 20:28:20.640803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a80d748549'
down_revision: Union[str, None] = '86eae84a81b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('content_length', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('screenshot', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'screenshot')
    op.drop_column('assets', 'content_length')
    op.drop_column('assets', 'status_code')
    op.drop_column('assets', 'title')
    # ### end Alembic commands ###
