"""add_all_security_domain_tables

Revision ID: 7f7dd85528c0
Revises: e54476c6bcdf
Create Date: 2026-09-14 02:41:17.939239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f7dd85528c0'
down_revision: Union[str, None] = 'e54476c6bcdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitre_techniques',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tactic', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threat_actors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('targeted_industries', sa.JSON(), nullable=True),
    sa.Column('targeted_countries', sa.JSON(), nullable=True),
    sa.Column('malware_used', sa.JSON(), nullable=True),
    sa.Column('ttps', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('threat_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('objective', sa.String(length=255), nullable=True),
    sa.Column('malware', sa.JSON(), nullable=True),
    sa.Column('iocs_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('first_seen', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threat_malware',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('families', sa.JSON(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_org_id'), 'ai_conversations', ['org_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_table('code_repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=True),
    sa.Column('secrets_count', sa.Integer(), nullable=True),
    sa.Column('last_scan', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'url')
    )
    op.create_index(op.f('ix_code_repositories_org_id'), 'code_repositories', ['org_id'], unique=False)
    op.create_table('detection_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_id_code', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('logic', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('matches_count', sa.Integer(), nullable=True),
    sa.Column('last_triggered', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_rules_org_id'), 'detection_rules', ['org_id'], unique=False)
    op.create_table('escalation_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('incidents_count', sa.Integer(), nullable=True),
    sa.Column('last_triggered', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_policies_org_id'), 'escalation_policies', ['org_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('incident_code', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('ttp', sa.String(length=100), nullable=True),
    sa.Column('iocs_count', sa.Integer(), nullable=True),
    sa.Column('assets_count', sa.Integer(), nullable=True),
    sa.Column('events_count', sa.Integer(), nullable=True),
    sa.Column('attack_chain', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_org_id'), 'incidents', ['org_id'], unique=False)
    op.create_index('ix_incidents_org_severity', 'incidents', ['org_id', 'severity'], unique=False)
    op.create_index('ix_incidents_org_status', 'incidents', ['org_id', 'status'], unique=False)
    op.create_table('integration_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'provider')
    )
    op.create_index(op.f('ix_integration_configs_org_id'), 'integration_configs', ['org_id'], unique=False)
    op.create_table('network_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('hosts_count', sa.Integer(), nullable=True),
    sa.Column('ports_count', sa.Integer(), nullable=True),
    sa.Column('services_count', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_scans_org_id'), 'network_scans', ['org_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_org_id'), 'notifications', ['org_id'], unique=False)
    op.create_table('report_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.String(length=50), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('download_url', sa.String(length=1024), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_records_org_id'), 'report_records', ['org_id'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('target', sa.String(length=512), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_occurred_at'), 'security_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_security_events_org_id'), 'security_events', ['org_id'], unique=False)
    op.create_table('subdomains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=512), nullable=False),
    sa.Column('parent_domain', sa.String(length=255), nullable=True),
    sa.Column('ips', sa.JSON(), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('discoveries', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'domain')
    )
    op.create_index(op.f('ix_subdomains_domain'), 'subdomains', ['domain'], unique=False)
    op.create_index(op.f('ix_subdomains_org_id'), 'subdomains', ['org_id'], unique=False)
    op.create_index(op.f('ix_subdomains_parent_domain'), 'subdomains', ['parent_domain'], unique=False)
    op.create_table('threat_iocs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('reputation', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('asn', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('malware', sa.JSON(), nullable=True),
    sa.Column('campaigns', sa.JSON(), nullable=True),
    sa.Column('ttps', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_iocs_org_id'), 'threat_iocs', ['org_id'], unique=False)
    op.create_index(op.f('ix_threat_iocs_value'), 'threat_iocs', ['value'], unique=False)
    op.create_table('ai_investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('inv_code', sa.String(length=50), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_investigations_org_id'), 'ai_investigations', ['org_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('alert_code', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('events_count', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['detection_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_org_id'), 'alerts', ['org_id'], unique=False)
    op.create_index('ix_alerts_org_severity', 'alerts', ['org_id', 'severity'], unique=False)
    op.create_index('ix_alerts_org_status', 'alerts', ['org_id', 'status'], unique=False)
    op.create_table('incident_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('hostname', sa.String(length=512), nullable=False),
    sa.Column('impact', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_assets_incident_id'), 'incident_assets', ['incident_id'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    op.create_table('incident_iocs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('ioc_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_iocs_incident_id'), 'incident_iocs', ['incident_id'], unique=False)
    op.create_table('incident_timelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_timelines_incident_id'), 'incident_timelines', ['incident_id'], unique=False)
    op.create_table('network_scan_hosts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('hostname', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('os_match', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['network_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_scan_hosts_scan_id'), 'network_scan_hosts', ['scan_id'], unique=False)
    op.create_table('network_scan_ports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['network_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_scan_ports_scan_id'), 'network_scan_ports', ['scan_id'], unique=False)
    op.create_table('network_scan_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['network_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_scan_services_scan_id'), 'network_scan_services', ['scan_id'], unique=False)
    op.create_table('response_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('action_code', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=512), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_actions_org_id'), 'response_actions', ['org_id'], unique=False)
    op.create_table('secret_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('secret_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('commit_hash', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('raw_preview', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['code_repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_findings_org_id'), 'secret_findings', ['org_id'], unique=False)
    op.create_index(op.f('ix_secret_findings_repo_id'), 'secret_findings', ['repo_id'], unique=False)
    op.create_table('subdomain_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subdomain_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subdomain_id'], ['subdomains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subdomain_history_subdomain_id'), 'subdomain_history', ['subdomain_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['security_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_alert_id'), 'alert_events', ['alert_id'], unique=False)
    op.add_column('vulnerabilities', sa.Column('assignee', sa.String(length=255), nullable=True))
    op.add_column('vulnerability_scans', sa.Column('target', sa.String(length=512), nullable=True))
    op.add_column('vulnerability_scans', sa.Column('engine', sa.String(length=50), nullable=True))
    op.add_column('vulnerability_scans', sa.Column('critical_count', sa.Integer(), nullable=True))
    op.add_column('vulnerability_scans', sa.Column('high_count', sa.Integer(), nullable=True))
    op.add_column('vulnerability_scans', sa.Column('medium_count', sa.Integer(), nullable=True))
    op.add_column('vulnerability_scans', sa.Column('low_count', sa.Integer(), nullable=True))
    op.add_column('vulnerability_scans', sa.Column('duration', sa.String(length=50), nullable=True))
    op.add_column('vulnerability_scans', sa.Column('schedule', sa.String(length=50), nullable=True))
    op.add_column('vulnerability_scans', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('vulnerability_scans', 'asset_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vulnerability_scans', 'asset_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('vulnerability_scans', 'created_at')
    op.drop_column('vulnerability_scans', 'schedule')
    op.drop_column('vulnerability_scans', 'duration')
    op.drop_column('vulnerability_scans', 'low_count')
    op.drop_column('vulnerability_scans', 'medium_count')
    op.drop_column('vulnerability_scans', 'high_count')
    op.drop_column('vulnerability_scans', 'critical_count')
    op.drop_column('vulnerability_scans', 'engine')
    op.drop_column('vulnerability_scans', 'target')
    op.drop_column('vulnerabilities', 'assignee')
    op.drop_index(op.f('ix_alert_events_alert_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_subdomain_history_subdomain_id'), table_name='subdomain_history')
    op.drop_table('subdomain_history')
    op.drop_index(op.f('ix_secret_findings_repo_id'), table_name='secret_findings')
    op.drop_index(op.f('ix_secret_findings_org_id'), table_name='secret_findings')
    op.drop_table('secret_findings')
    op.drop_index(op.f('ix_response_actions_org_id'), table_name='response_actions')
    op.drop_table('response_actions')
    op.drop_index(op.f('ix_network_scan_services_scan_id'), table_name='network_scan_services')
    op.drop_table('network_scan_services')
    op.drop_index(op.f('ix_network_scan_ports_scan_id'), table_name='network_scan_ports')
    op.drop_table('network_scan_ports')
    op.drop_index(op.f('ix_network_scan_hosts_scan_id'), table_name='network_scan_hosts')
    op.drop_table('network_scan_hosts')
    op.drop_index(op.f('ix_incident_timelines_incident_id'), table_name='incident_timelines')
    op.drop_table('incident_timelines')
    op.drop_index(op.f('ix_incident_iocs_incident_id'), table_name='incident_iocs')
    op.drop_table('incident_iocs')
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_incident_assets_incident_id'), table_name='incident_assets')
    op.drop_table('incident_assets')
    op.drop_index('ix_alerts_org_status', table_name='alerts')
    op.drop_index('ix_alerts_org_severity', table_name='alerts')
    op.drop_index(op.f('ix_alerts_org_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_ai_investigations_org_id'), table_name='ai_investigations')
    op.drop_table('ai_investigations')
    op.drop_index(op.f('ix_threat_iocs_value'), table_name='threat_iocs')
    op.drop_index(op.f('ix_threat_iocs_org_id'), table_name='threat_iocs')
    op.drop_table('threat_iocs')
    op.drop_index(op.f('ix_subdomains_parent_domain'), table_name='subdomains')
    op.drop_index(op.f('ix_subdomains_org_id'), table_name='subdomains')
    op.drop_index(op.f('ix_subdomains_domain'), table_name='subdomains')
    op.drop_table('subdomains')
    op.drop_index(op.f('ix_security_events_org_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_occurred_at'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_report_records_org_id'), table_name='report_records')
    op.drop_table('report_records')
    op.drop_index(op.f('ix_notifications_org_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_network_scans_org_id'), table_name='network_scans')
    op.drop_table('network_scans')
    op.drop_index(op.f('ix_integration_configs_org_id'), table_name='integration_configs')
    op.drop_table('integration_configs')
    op.drop_index('ix_incidents_org_status', table_name='incidents')
    op.drop_index('ix_incidents_org_severity', table_name='incidents')
    op.drop_index(op.f('ix_incidents_org_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_escalation_policies_org_id'), table_name='escalation_policies')
    op.drop_table('escalation_policies')
    op.drop_index(op.f('ix_detection_rules_org_id'), table_name='detection_rules')
    op.drop_table('detection_rules')
    op.drop_index(op.f('ix_code_repositories_org_id'), table_name='code_repositories')
    op.drop_table('code_repositories')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_conversations_org_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_table('threat_malware')
    op.drop_table('threat_campaigns')
    op.drop_table('threat_actors')
    op.drop_table('mitre_techniques')
    # ### end Alembic commands ###
