"""assets and discovery

Revision ID: 86eae84a81b8
Revises: b97d41387333
Create Date: 2026-09-13 20:05:58.828464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86eae84a81b8'
down_revision: Union[str, None] = 'b97d41387333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=512), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('discovered_by', sa.String(length=100), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'hostname')
    )
    op.create_index(op.f('ix_assets_domain'), 'assets', ['domain'], unique=False)
    op.create_index(op.f('ix_assets_org_id'), 'assets', ['org_id'], unique=False)
    op.create_index('ix_assets_org_status', 'assets', ['org_id', 'status'], unique=False)
    op.create_index('ix_assets_org_type', 'assets', ['org_id', 'type'], unique=False)
    op.create_table('discovery_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('tool', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('findings', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_jobs_org_id'), 'discovery_jobs', ['org_id'], unique=False)
    op.create_table('asset_certs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('subject_cn', sa.String(length=255), nullable=True),
    sa.Column('issuer_cn', sa.String(length=255), nullable=True),
    sa.Column('san', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_certs_asset_id'), 'asset_certs', ['asset_id'], unique=False)
    op.create_table('asset_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_history_asset_id'), 'asset_history', ['asset_id'], unique=False)
    op.create_table('asset_ports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'port', 'protocol')
    )
    op.create_index(op.f('ix_asset_ports_asset_id'), 'asset_ports', ['asset_id'], unique=False)
    op.create_table('asset_tech',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_tech_asset_id'), 'asset_tech', ['asset_id'], unique=False)
    op.create_table('discovered_hosts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('host', sa.String(length=512), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('found_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['discovery_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovered_hosts_job_id'), 'discovered_hosts', ['job_id'], unique=False)
    op.create_index(op.f('ix_discovered_hosts_org_id'), 'discovered_hosts', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovered_hosts_org_id'), table_name='discovered_hosts')
    op.drop_index(op.f('ix_discovered_hosts_job_id'), table_name='discovered_hosts')
    op.drop_table('discovered_hosts')
    op.drop_index(op.f('ix_asset_tech_asset_id'), table_name='asset_tech')
    op.drop_table('asset_tech')
    op.drop_index(op.f('ix_asset_ports_asset_id'), table_name='asset_ports')
    op.drop_table('asset_ports')
    op.drop_index(op.f('ix_asset_history_asset_id'), table_name='asset_history')
    op.drop_table('asset_history')
    op.drop_index(op.f('ix_asset_certs_asset_id'), table_name='asset_certs')
    op.drop_table('asset_certs')
    op.drop_index(op.f('ix_discovery_jobs_org_id'), table_name='discovery_jobs')
    op.drop_table('discovery_jobs')
    op.drop_index('ix_assets_org_type', table_name='assets')
    op.drop_index('ix_assets_org_status', table_name='assets')
    op.drop_index(op.f('ix_assets_org_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_domain'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
