"""vulns exposures

Revision ID: e54476c6bcdf
Revises: 77a80d748549
Create Date: 2026-09-13 20:39:53.224531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e54476c6bcdf'
down_revision: Union[str, None] = '77a80d748549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exposures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('affected_identity', sa.String(length=512), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mask', sa.String(length=255), nullable=True),
    sa.Column('secret_type', sa.String(length=50), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exposure_org_type', 'exposures', ['org_id', 'type'], unique=False)
    op.create_index(op.f('ix_exposures_affected_identity'), 'exposures', ['affected_identity'], unique=False)
    op.create_index(op.f('ix_exposures_org_id'), 'exposures', ['org_id'], unique=False)
    op.create_table('exposure_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exposure_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exposure_id'], ['exposures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exposure_events_exposure_id'), 'exposure_events', ['exposure_id'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('cve', sa.String(length=50), nullable=True),
    sa.Column('template_id', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('cvss', sa.Float(), nullable=True),
    sa.Column('cwe', sa.String(length=20), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('matched_at', sa.String(length=500), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vuln_org_severity', 'vulnerabilities', ['org_id', 'severity'], unique=False)
    op.create_index('ix_vuln_org_status', 'vulnerabilities', ['org_id', 'status'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_asset_id'), 'vulnerabilities', ['asset_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_cve'), 'vulnerabilities', ['cve'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_org_id'), 'vulnerabilities', ['org_id'], unique=False)
    op.create_table('vulnerability_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('tool', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('findings', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['discovery_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerability_scans_asset_id'), 'vulnerability_scans', ['asset_id'], unique=False)
    op.create_index(op.f('ix_vulnerability_scans_org_id'), 'vulnerability_scans', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerability_scans_org_id'), table_name='vulnerability_scans')
    op.drop_index(op.f('ix_vulnerability_scans_asset_id'), table_name='vulnerability_scans')
    op.drop_table('vulnerability_scans')
    op.drop_index(op.f('ix_vulnerabilities_org_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cve'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_asset_id'), table_name='vulnerabilities')
    op.drop_index('ix_vuln_org_status', table_name='vulnerabilities')
    op.drop_index('ix_vuln_org_severity', table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_exposure_events_exposure_id'), table_name='exposure_events')
    op.drop_table('exposure_events')
    op.drop_index(op.f('ix_exposures_org_id'), table_name='exposures')
    op.drop_index(op.f('ix_exposures_affected_identity'), table_name='exposures')
    op.drop_index('ix_exposure_org_type', table_name='exposures')
    op.drop_table('exposures')
    # ### end Alembic commands ###
